{{- if .Values.mpcOperatorCheck.kmsCore.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: mpc-operator-check-kms-core
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 0
  completionMode: Indexed
  backoffLimitPerIndex: 1
  maxFailedIndexes: 1
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished | int }}
  template:
    metadata:
      labels:
        app: mpc-operator-check
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.awsCli.enabled }}
        - name: aws-check
          image: {{ .Values.awsCli.image.repository }}:{{ .Values.awsCli.image.tag }}
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              echo "=================================================="
              {{- .Values.awsCli.script | nindent 14 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
        {{- end }}
        {{- if .Values.kubectl.enabled }}
        - name: kubernetes-namespace-check
          image: {{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              echo "=================================================="
              {{- .Values.kubectl.script | nindent 14 }}
              echo "=================================================="
              echo "Kubernetes enclave nodes check"
              kubectl describe node -l node.kubernetes.io/enclave-enabled=true
              echo "=================================================="
              echo "Check kms-core logs"
              kubectl logs -l app=kms-core --prefix -c kms-core-enclave-logger
        {{- end }}
        {{- if .Values.netcat.enabled }}
        - name: netcat-check
          image: {{ .Values.netcat.image.repository }}:{{ .Values.netcat.image.tag }}
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              echo "=================================================="
              {{- .Values.netcat.script | nindent 14 }}
              exit 0
        {{- end }}
        {{- if .Values.kmsCoreClient.enabled }}
        - name: kms-config
          image: {{ .Values.utils.image.repository }}:{{ .Values.utils.image.tag }}
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              # Substitute env vars into kms-server.toml
              envsubst < /chart-config/kms-server.toml > /config/kms-server.toml
              envsubst < /chart-config/vaults.toml >> /config/kms-server.toml
              # Copy enclave config to config workdir
              cp /chart-config/enclave.json /config/enclave.json
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
          volumeMounts:
            - name: chart-config
              mountPath: /chart-config
            - name: config
              mountPath: /config
      containers:
        - name: run-kms-health-check
          image: {{ .Values.kmsCoreClient.image.repository }}:{{ .Values.kmsCoreClient.image.tag }}
          imagePullPolicy: Always
          workingDir: /config
          command:
            - /bin/sh
            - -c
            - |
              echo "=================================================="
              echo "Executing {{ .Chart.Name }}:{{ .Chart.Version }}"
              echo "=================================================="
              {{- .Values.kmsCoreClient.script | nindent 14 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          emptyDir: {}
        - name: chart-config
          configMap:
            name: {{ .Values.kmsCoreClient.configmap.name }}
            items:
              - key: enclave.json
                path: enclave.json
              - key: kms-server.toml
                path: kms-server.toml
              - key: vaults.toml
                path: vaults.toml
      {{- else }}
      containers:
        - name: kube-utils
          image: {{ .Values.utils.image.repository }}:{{ .Values.utils.image.tag }}
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              echo "=================================================="
              {{- .Values.utils.script | nindent 14 }}
      {{- end }}
      restartPolicy: Never
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}