{{- if and .Values.kubectl.enabled (or .Values.mpcOperatorCheck.kmsCore.enabled .Values.mpcOperatorCheck.kmsConnector.enabled)}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mpc-operator-check-resource-reader
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mpc-operator-check
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
subjects:
  {{- if .Values.mpcOperatorCheck.kmsCore.enabled }}
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.mpcOperatorCheck.kmsConnector.enabled }}
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}-connector
    namespace: {{ .Release.Namespace }}
  {{- end }}
roleRef:
  kind: ClusterRole
  name: mpc-operator-check-resource-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
